### ISSUE TITLE
Requesting new code to download .gguf files

### ISSUE THREAD

**Issue by adnanPBI** [Dicklesworthstone/llm_aided_ocr#5]
Hi,
As per your code instruction, llma2 chat ggml files will be downloaded but currently 'TheBloke' recommends downloading gguf models instead of ggml files. So, can you provide new code stating to download gguf files from repository?
Thanks.

**Comment by Dicklesworthstone** [comment]
It’s a quite easy change to make; you’re welcome to make a PR for it.
ChatGPT could easily tell you how to do it. Good luck.

**Comment by adnanPBI** [comment]
Do I have to download the whole repository like before or I can download
definite version?

**Comment by Dicklesworthstone** [comment]
Not sure what you’re asking here. If you want to modify the code for your
purposes then you should clone the repo locally and make your changes there.

**Comment by adnanPBI** [comment]
I tried the "huggingface-cli download TheBloke/Llama-2-13B-chat-GGUF llama-2-13b-chat.q4_K_M.gguf --local-dir" in multiple ways to download single GGUF file but every time getting error. That's why I gave knock to you.

**Comment by adnanPBI** [comment]
I was looking for a solution to apply gguf files on your supplied
python code snippet in the issue section. Can you please suggest me a
solution?
